/**
 * Non-interactive setup for LLM agents and automation
 */

import { writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';

interface NonInteractiveConfig {
  databaseType?: string;
  databaseUrl?: string;
  databasePath?: string;
  llmProvider?: string;
  llmModel?: string;
  llmApiKey?: string;
  redisUrl?: string;
  enableL2Cache?: boolean;
  embeddingApiKey?: string;
}

const LLM_MODELS: Record<string, string> = {
  anthropic: 'claude-sonnet-4-5-20250929',
  openai: 'gpt-4o',
  cohere: 'command-r-plus',
  mistral: 'mistral-large-latest',
  google: 'gemini-pro',
};

export function runNonInteractiveSetup(options: NonInteractiveConfig): void {
  console.log('🤖 Running non-interactive setup...\n');

  // Validate required options
  const errors: string[] = [];

  if (!options.databaseType) {
    errors.push('--database-type is required (pg, mysql2, better-sqlite3, mssql)');
  }

  if (options.databaseType === 'better-sqlite3') {
    if (!options.databasePath) {
      errors.push('--database-path is required for SQLite');
    }
  } else {
    if (!options.databaseUrl) {
      errors.push('--database-url is required');
    }
  }

  if (!options.llmProvider) {
    errors.push('--llm-provider is required (anthropic, openai, cohere, mistral, google)');
  }

  if (!options.llmApiKey) {
    errors.push('--llm-api-key is required');
  }

  if (options.enableL2Cache && !options.embeddingApiKey) {
    errors.push('--embedding-api-key is required when --enable-l2-cache is set');
  }

  if (errors.length > 0) {
    console.error('❌ Configuration errors:\n');
    errors.forEach(err => console.error(`  • ${err}`));
    console.error('\n💡 Example usage:');
    console.error('  npx nttp setup --non-interactive \\');
    console.error('    --database-type=pg \\');
    console.error('    --database-url=postgresql://user:pass@localhost/db \\');
    console.error('    --llm-provider=anthropic \\');
    console.error('    --llm-api-key=sk-ant-... \\');
    console.error('    --redis-url=redis://localhost:6379 \\');
    console.error('    --enable-l2-cache \\');
    console.error('    --embedding-api-key=sk-...');
    process.exit(1);
  }

  // Auto-fill model if not provided
  const llmModel = options.llmModel || LLM_MODELS[options.llmProvider!];

  console.log('✓ Configuration validated');
  console.log('✓ Creating .env file...');

  // Generate .env file
  const envLines = [
    '# nttp configuration',
    '# Generated by nttp setup --non-interactive',
    '',
    '# Database',
  ];

  if (options.databaseType === 'better-sqlite3') {
    envLines.push(`DATABASE_PATH=${options.databasePath}`);
  } else {
    envLines.push(`DATABASE_URL=${options.databaseUrl}`);
  }

  envLines.push(`DATABASE_TYPE=${options.databaseType}`);
  envLines.push('');
  envLines.push('# LLM Provider');
  envLines.push(`LLM_PROVIDER=${options.llmProvider}`);
  envLines.push(`LLM_MODEL=${llmModel}`);

  const envKeys: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openai: 'OPENAI_API_KEY',
    cohere: 'COHERE_API_KEY',
    mistral: 'MISTRAL_API_KEY',
    google: 'GOOGLE_API_KEY',
  };

  envLines.push(`${envKeys[options.llmProvider!]}=${options.llmApiKey}`);

  if (options.redisUrl) {
    envLines.push('');
    envLines.push('# Redis Cache');
    envLines.push(`REDIS_URL=${options.redisUrl}`);
  }

  if (options.enableL2Cache) {
    envLines.push('');
    envLines.push('# Semantic Cache');
    envLines.push('EMBEDDING_PROVIDER=openai');
    envLines.push(`OPENAI_API_KEY=${options.embeddingApiKey}`);
  }

  writeFileSync('.env', envLines.join('\n') + '\n');
  console.log('✓ .env created');

  // Generate example code
  console.log('✓ Creating nttp-example.js...');
  const code = `/**
 * NTTP Example - Ready to run!
 * Run: node nttp-example.js or npm start
 */

import 'dotenv/config';
import { NTTP } from 'nttp';

async function main() {
  // Load configuration from .env
  const nttp = await NTTP.fromEnv();

  console.log('✓ Connected to database');

  // Run a natural language query
  const result = await nttp.query('show me 5 records');

  console.log(\`\\n✓ Query succeeded! Got \${result.data.length} rows\`);
  console.log(\`  Generated SQL: \${result.sql}\`);
  console.log(\`  Cache hit: \${result.cacheHit}\`);
  console.log(\`  Time: \${result.executionTimeMs}ms\\n\`);

  // Display results
  console.table(result.data);

  // Cleanup
  await nttp.close();
}

main().catch(console.error);
`;

  writeFileSync('nttp-example.js', code);
  console.log('✓ nttp-example.js created');

  // Create package.json if it doesn't exist
  if (!existsSync('package.json')) {
    console.log('✓ Creating package.json...');
    const packageJson = {
      name: 'nttp-project',
      version: '1.0.0',
      type: 'module',
      scripts: {
        start: 'node nttp-example.js'
      }
    };
    writeFileSync('package.json', JSON.stringify(packageJson, null, 2));
    console.log('✓ package.json created');
  }

  // Install dependencies
  console.log('✓ Installing dependencies (nttp, dotenv)...');
  try {
    execSync('npm install nttp dotenv', { stdio: 'inherit' });
    console.log('✓ Dependencies installed');
  } catch (error) {
    console.error('⚠ Failed to install dependencies. Please run: npm install nttp dotenv');
  }

  // Success message
  console.log('\n✅ Setup complete!\n');
  console.log('Created:');
  console.log('  • .env (your configuration)');
  console.log('  • nttp-example.js (example code)');
  console.log('  • package.json (if not exists)');
  console.log('  • node_modules/ (installed nttp, dotenv)\n');
  console.log('Next steps:');
  console.log('  1. Try CLI: npx nttp query "show me 5 records"');
  console.log('  2. Or run code: node nttp-example.js');
  console.log('  3. Or use in your code: npm start\n');
}
